### ISSUE TITLE
s3 input with cloudtrail codec

### ISSUE THREAD

**Issue by cdenneen** [elasticsearch/logstash-contrib#154]
Currently what input does the cloudtrail codec work with? Documentation isn't clear but using with s3 input ingests raw json into message.

**Comment by untergeek** [comment]
Sorry for the runaround.

Can you please open this issue against either (or both) of the plugins you mentioned? All plugins are now in their own respective repositories:

https://github.com/logstash-plugins/logstash-input-s3
https://github.com/logstash-plugins/logstash-codec-cloudtrail

Thanks!
