### ISSUE TITLE
S3 output on windows - no absolute path.

### ISSUE THREAD

**Issue by SleeperSmith** [elasticsearch/logstash-contrib#74]
Version 1.4.1

When I try to use S3 output on windows, an error saying

Neither current working directory (null) nor /opt/\<blah blah> resolve to absolute path.

Throws an exception, continues to log into S3_temp (the part file keeps growing). As far as I have seen, it just throws once and never tries again.

On a side note, there's also a bug with S3_temp path. I have put logstash in D:\logstash. It opens a file in D:\logstash\opt\\\<blah>\S3_temp\ and then proceeds to log into D:\opt\\\<blah>\S3_temp\

**Comment by wiibaa** [comment]
@ph can you please confirm this is fixed for 1.5 in https://github.com/logstash-plugins/logstash-output-s3/ ?

**Comment by ph** [comment]
Yes it is solved, in the next version of the plugin we are using the OS tmp dir as the default, so you will get `/tmp/logstash` on unix. But you can now override it using the `temporary_directory` option.
